apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: saas-provider
  name: saas-provider-backend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: saas-provider-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: saas-provider-backend
    spec:
      containers:
      - name: saas-provider-backend
        image: 427398298435.dkr.ecr.us-east-2.amazonaws.com/saas-provider-backend:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: provider
              key: GITHUB_TOKEN
        - name: GITHUB_USER
          valueFrom:
            secretKeyRef:
              name: provider
              key: GITHUB_USER
        - name: GITHUB_TEMPLATED_REPO
          valueFrom:
            secretKeyRef:
              name: provider
              key: GITHUB_TEMPLATED_REPO
        volumeMounts:
          - name: api-data
            mountPath: /data
        ports:
          - containerPort: 80
      volumes:
      - name: api-data
        persistentVolumeClaim:
          claimName: provider-backend-data
