apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: saas-provider-backend
  name: saas-provider-backend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: saas-provider-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: saas-provider-backend
    spec:
      containers:
      - name: saas-provider-backend
        image: 427398298435.dkr.ecr.us-east-2.amazonaws.com/saas-provider-backend:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: provider-backend
              key: GITHUB_TOKEN
        - name: GITHUB_USER
          valueFrom:
            secretKeyRef:
              name: provider-backend
              key: GITHUB_USER
        - name: GITHUB_TEMPLATED_REPO
          valueFrom:
            secretKeyRef:
              name: provider-backend
              key: GITHUB_TEMPLATED_REPO
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: provider-backend
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: provider-backend
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: api-data
            mountPath: /data
        ports:
          - containerPort: 8080
            hostPort: 8080
      volumes:
      - name: api-data
        persistentVolumeClaim:
          claimName: provider-backend-data
