apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provider-backend-data
  namespace: saas-provider
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
